# Generated by Django 4.1.7 on 2023-03-27 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 16, 46, 1, 110860, tzinfo=datetime.timezone.utc)),
        ),
    ]
