# Generated by Django 4.1.7 on 2023-03-28 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_customtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 4, 25, 38, 287613, tzinfo=datetime.timezone.utc)),
        ),
    ]
